DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT (
student_roll INT AUTO_INCREMENT  PRIMARY KEY,
student_name VARCHAR(255) NOT NULL,
student_age INT NOT NULL
);

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE (
course_name VARCHAR(255) PRIMARY KEY,
course_code VARCHAR(255) NOT NULL,
course_description VARCHAR(255) NOT NULL
);



